from openvino import Model

class GeneralFailure(Exception): ...
class InitializationFailure(Exception): ...
class NotImplementedFailure(Exception): ...
class OpConversionFailure(Exception): ...
class OpValidationFailure(Exception): ...
class InputModel: ...

class FrontEnd:
    def load(self, path: str) -> InputModel | None: ...
    def convert(self, model: InputModel) -> Model: ...

class FrontEndManager:
    def load_by_framework(self, framework: str) -> FrontEnd | None: ...
