"""Narrow 2026.4 integration surface; upstream stubs disable their own exports."""

from collections.abc import Mapping

class Node:
    def get_friendly_name(self) -> str: ...
    def get_type_name(self) -> str: ...

class Model:
    def get_ops(self) -> list[Node]: ...

class Version:
    build_number: str

class Core:
    def get_property(self, device_name: str, name: str) -> object: ...
    def get_versions(self, device_name: str) -> dict[str, Version]: ...
    def query_model(
        self, model: Model, device_name: str, config: Mapping[str, str | int]
    ) -> object: ...
    def compile_model(
        self, model: Model, device_name: str, config: Mapping[str, str | int]
    ) -> object: ...

def get_version() -> str: ...
